### ISSUE TITLE
Add SYNO.SurveillanceStation API from snjoetw/py-synology

### ISSUE THREAD

**Issue by Quentame** [ProtoThis/python-synology#53]
Hi @snjoetw & @shenxn !

While looking at home-assistant/core#35821 and the library https://github.com/snjoetw/py-synology ...

I propose we merge libraries !

Since we are all using the same devices, and use the same APIs !

So in one library :
- we can fetch all APIs available in our NAS (`get` and `post` functions)
- access to already wrapped APIs:
  - `SYNO.API.Info`
  - `SYNO.Core.SecurityScan.Status`
  - `SYNO.Core.System.Utilization`
  - `SYNO.DSM.Info`
  - `SYNO.DSM.Network`
  - `SYNO.Storage.CGI.Storage`
- access to `SurveillanceStation`
- access to `DownloadStation` (planned to be added soon)

Benefits for Home Assistant:
- Authentication from `synology_dsm` and `synology` (Surveillance Station) won't collide, or won't need two users
- Adding `synology_dsm` will also add SurveillanceStation automatically (as a separate device)
- Users won't configure two integrations for one device (integrations params are the same besides `timeout`)
- Will drastically reduce the amount of code since we just need to add & maintain a new `camera` platform and avoid copy of  `__init__.py`, `config_flow.py`, ... cf @home-assistant/core#35821
- @snjoetw & @shenxn could maintain the camera platform, me @Quentame the rest :joy: 

What do you think ?

---

Steps:
- [x] #56 Add a `timeout` param
- [x] #59 Refactor the existing wrapper code so we don't use `@property` to retreive API, and don't need to `reset` if we don't want to update them.
- [x] #57 Add SYNO.SurveillanceStation API from https://github.com/snjoetw/py-synology

I personally don't have cameras linked to my DSM SurveillanceStation, but I can propose code for someone to test and open my repo so we can collaborate.

Using this library will also prevent manual payload build, from something automatic. 

---

Cc @alexguzun (I don't forget home-assistant/core#30970)

**Comment by shenxn** [comment]
I agree with that. It'll save a lot of time for both maintainers and users.

**Comment by Quentame** [comment]
@shenxn Are you in the HA Discord ? https://discord.gg/NAKujAp
So we can chat faster on some details.

I will  work on `timeout` and `property` aspect very soon.
Drafting a PR for Surveillance, and will ping you for tests ?

**Comment by shenxn** [comment]
@Quentame I just added my self into HA Discord. I'd be happy to do some tests. Just ping me when you need it.

**Comment by Quentame** [comment]
@shenxn Maybe we can also take care of home-assistant/core#29931 in the meantime.

Added `SYNO.SurveillanceStation.Camera`.`getLiveViewPath` to take care of live stream paths (mjpeg, multicast, mxpeg & RTSP), see the draft PR #57 :wink: 

When you test, put `debugmode` to True.
Then, can you provide me some paylog ?

So I can add some unit test.

Take care of `get_camera_image` and `download_snapshot`, which return a JPEG file instead of JSON text.

Maybe you can use the `for-testers` branch, with a rebase and some adaptation, to test easily.

**Comment by Quentame** [comment]
API added
